---
- name: Ensure Nginx is at the latest version
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: true

- name: Start Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Configure nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: "0755"
  notify: nginx reload
